### ISSUE TITLE
Rename bs4 to beautifulsoup4

### ISSUE THREAD

**Issue by papoteur-mga** [shlomif/rebookmaker#1]
Hi Shlomif,
In requirements, you have bs4. But the normal name is beautifulsoup4
https://pypi.org/project/bs4/

> This is a dummy package managed by the developer of Beautiful Soup to prevent name squatting. The official name of PyPI’s Beautiful Soup Python package is [beautifulsoup4](https://pypi.python.org/pypi/beautifulsoup4).

**Comment by shlomif** [comment]
On Sun, 18 Jun 2023 08:27:15 -0700
Papoteur ***@***.***> wrote:

> Hi Shlomif,
> In requirements, you have bs4. But the normal name is beautifulsoup4
> https://pypi.org/project/bs4/
> 
> > This is a dummy package managed by the developer of Beautiful Soup to
> > prevent name squatting. The official name of PyPI’s Beautiful Soup Python
> > package is [beautifulsoup4](https://pypi.python.org/pypi/beautifulsoup4).  
> 

Thanks! I'll try to fix it

-- 

Shlomi Fish       https://www.shlomifish.org/
Perl Elems to Avoid - https://perl-begin.org/tutorials/bad-elements/

Barth's Distinction:  There are two types of people: those who divide people
into two types, and those who don't.
    — via fortune-mod.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
shouldbe fixed. thanks.
